name: visual_rl_benchmark
channels:
  - conda-forge
dependencies:
  - conda-forge::python=3.10
  - pip
  - pip:
      - opencv-python-headless==4.10.0.84
      - numpy==2.1.3
      - diffusers
      - transformers
      - torch
      - accelerate